# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvbsazxblCbMnSyqyBerBfV5bq4mDVLm
"""

print("Kod programu")

"""Przykładowy tekst - Plik powyżej jest kodem"""

a = 5
print(a)

"""Tekst, który został zaprezentowany to liczba 5"""
